site_name: Öğretici Paket
repo_url: https://github.com/ibrahimguney/web-proje
theme:
  name: material
nav:
  - Ana Sayfa: index.md
  - Kurulum: installation.md
  - Kullanım: usage.md
  - İstatistik:
      - Giriş: statistics/index.md
      - Ders Planı: statistics/plan.md
      - Kaynaklar: statistics/resources.md
